# Generated by Django 3.2.8 on 2021-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_auto_20211011_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='descr'),
        ),
    ]
