# Generated by Django 3.2.8 on 2021-10-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0004_rename_description_menuitem_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
