# Generated by Django 3.2.8 on 2021-10-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='number', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='item', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(default='price', max_length=255),
        ),
    ]
