# Generated by Django 3.2.8 on 2021-10-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211012_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='title',
        ),
    ]
