# Generated by Django 3.2.8 on 2021-10-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_name_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.JSONField(null=True),
        ),
    ]
