# Generated by Django 3.2.8 on 2021-10-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.JSONField(null=True),
        ),
    ]
